apiVersion: v1
kind: ReplicationController
metadata:
  name: web-api-replication
  labels:
    name: web-api-replication
    type: api-replication
    tier: api
    env: dev
spec:
  template:
    metadata:
      name: web-api-pod
      labels:
        name: web-api
        type: net-core-api
        tier: api
        env: dev
    spec:
      containers:
        - name: docker-web-api
          image: rudibrits/docker-web-api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+
            - name: USER_SECRETS_PATH
              value: C:\Users\orbri\AppData\Roaming\microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro
            - name: ASP_NET_HTTPS_PATH
              value: C:\Users\orbri\.aspnet\https:/root/.aspnet/https/:ro
  replicas: 4
