apiVersion: v1
kind: Service
metadata:
  name: web-api2-load-balancer-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30004
  selector:
    type: web-api2-pod
